from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import tempfile
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable

from .db import RuntimeDB
from .skill_format import (
    MAX_INSTRUCTIONS_TOKENS,
    MAX_PACKAGE_BYTES,
    REQUIRED_DIRECTORIES,
    REQUIRED_FIELDS,
)


GENERATOR_VERSION = 1
ARTIFACTS = (
    "architecture-map.md",
    "api-reference.md",
    "cli-reference.md",
    "skill-format.md",
    "memory-schema.md",
    "provider-setup.md",
    "troubleshooting.md",
)


def _hash_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _hash_text(value: str) -> str:
    return _hash_bytes(value.encode("utf-8"))


def _canonical(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def _table_text(value: str) -> str:
    return value.replace("|", "\\|")


def _source_digest(root: Path) -> str:
    runtime = root / "acr_runtime"
    if not runtime.is_dir():
        raise ValueError("Repository must contain acr_runtime/")
    digest = hashlib.sha256()
    files = sorted(
        (
            path for path in runtime.rglob("*.py")
            if "__pycache__" not in path.parts
        ),
        key=lambda path: path.relative_to(root).as_posix(),
    )
    if not files:
        raise ValueError("No runtime Python sources found")
    for path in files:
        relative = path.relative_to(root).as_posix()
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
    return digest.hexdigest()


def _header(title: str, source_digest: str) -> list[str]:
    return [
        f"# {title}",
        "",
        "<!-- Generated by acr docs propose-reference. Do not edit directly. -->",
        f"Source digest: `{source_digest}`",
        "",
    ]


def _module_name(root: Path, path: Path) -> str:
    return path.relative_to(root).with_suffix("").as_posix().replace("/", ".")


def _architecture(root: Path, source_digest: str) -> str:
    lines = _header("Architecture map", source_digest)
    lines.extend([
        "The map is derived from top-level Python module declarations and "
        "internal imports.",
        "",
        "| Module | Purpose | Internal dependencies |",
        "| --- | --- | --- |",
    ])
    for path in sorted((root / "acr_runtime").glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        module_doc = ast.get_docstring(tree)
        primary = next(
            (
                node for node in tree.body
                if isinstance(node, (ast.ClassDef, ast.FunctionDef))
                and not node.name.startswith("_")
            ),
            None,
        )
        primary_doc = ast.get_docstring(primary) if primary is not None else None
        purpose = (
            module_doc.splitlines()[0]
            if module_doc
            else primary_doc.splitlines()[0]
            if primary_doc
            else f"Defines `{primary.name}`."
            if primary is not None
            else "Package declarations and constants."
        )
        dependencies: set[str] = set()
        for node in tree.body:
            if isinstance(node, ast.ImportFrom) and node.level:
                module = node.module or ""
                dependencies.add(module.split(".", 1)[0] or "(package)")
        rendered = ", ".join(f"`{item}`" for item in sorted(dependencies)) or "—"
        lines.append(
            f"| `{_module_name(root, path)}` | "
            f"{_table_text(purpose)} | {rendered} |"
        )
    return "\n".join(lines) + "\n"


def _api_reference(root: Path, source_digest: str) -> str:
    source = root / "acr_runtime" / "api.py"
    tree = ast.parse(source.read_text(encoding="utf-8"))
    endpoints: list[tuple[str, str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if (
                isinstance(decorator, ast.Call)
                and isinstance(decorator.func, ast.Attribute)
                and isinstance(decorator.func.value, ast.Name)
                and decorator.func.value.id == "app"
                and decorator.func.attr in {
                    "get", "post", "put", "patch", "delete"
                }
                and decorator.args
                and isinstance(decorator.args[0], ast.Constant)
                and isinstance(decorator.args[0].value, str)
            ):
                endpoints.append((
                    decorator.func.attr.upper(),
                    decorator.args[0].value,
                    node.name,
                ))
    lines = _header("API reference", source_digest)
    lines.extend([
        "FastAPI routes statically discovered from `acr_runtime/api.py`.",
        "",
        "| Method | Path | Handler |",
        "| --- | --- | --- |",
    ])
    for method, path, handler in sorted(endpoints, key=lambda item: (item[1], item[0])):
        lines.append(f"| `{method}` | `{path}` | `{handler}` |")
    return "\n".join(lines) + "\n"


def _cli_commands(
    parser: argparse.ArgumentParser,
    prefix: tuple[str, ...] = (),
) -> list[tuple[str, str]]:
    commands: list[tuple[str, str]] = []
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        help_by_name = {
            item.dest: item.help
            for item in action._choices_actions
        }
        for name, child in action.choices.items():
            path = (*prefix, name)
            commands.append((" ".join(path), help_by_name.get(name) or ""))
            commands.extend(_cli_commands(child, path))
    return commands


def _cli_reference(root: Path, source_digest: str) -> str:
    from .cli import _parser

    lines = _header("CLI reference", source_digest)
    lines.extend([
        "Commands discovered from the live `argparse` parser.",
        "",
        "| Command | Description |",
        "| --- | --- |",
    ])
    for command, description in _cli_commands(_parser()):
        lines.append(
            f"| `acr {command}` | {_table_text(description)} |"
        )
    return "\n".join(lines) + "\n"


def _skill_format(root: Path, source_digest: str) -> str:
    fields = sorted(REQUIRED_FIELDS)
    lines = _header("Skill format", source_digest)
    lines.extend([
        "The Skill Format v1 contract is derived from "
        "`acr_runtime/skill_format.py`.",
        "",
        f"- Maximum package bytes: `{MAX_PACKAGE_BYTES}`",
        f"- Maximum instruction tokens: `{MAX_INSTRUCTIONS_TOKENS}`",
        "- Required directories: "
        + ", ".join(f"`{item}/`" for item in REQUIRED_DIRECTORIES),
        "",
        "## Required manifest fields",
        "",
    ])
    lines.extend(f"- `{field}`" for field in fields)
    lines.extend([
        "",
        "Packages also require `SKILL.yaml`, `instructions.md`, and "
        "`history.jsonl`; symlinks and escaping paths are rejected.",
    ])
    return "\n".join(lines) + "\n"


def _memory_schema(root: Path, source_digest: str) -> str:
    with tempfile.TemporaryDirectory() as directory:
        database = RuntimeDB(Path(directory) / "schema.db")
        try:
            health = database.health()
            tables = database.connection.execute(
                """
                SELECT name FROM sqlite_master
                WHERE type='table' AND name NOT LIKE 'sqlite_%'
                ORDER BY name
                """
            ).fetchall()
            schema: list[tuple[str, str]] = []
            for row in tables:
                name = str(row["name"])
                quoted = '"' + name.replace('"', '""') + '"'
                columns = database.connection.execute(
                    f"PRAGMA table_info({quoted})"
                ).fetchall()
                rendered = ", ".join(
                    f"{column['name']}:{column['type'] or 'ANY'}"
                    for column in columns
                )
                schema.append((name, rendered))
        finally:
            database.close()
    lines = _header("Memory schema", source_digest)
    lines.extend([
        f"Fresh runtime schema version: `{health['schema_version']}`",
        f"Schema fingerprint valid: `{str(health['schema_fingerprint_valid']).lower()}`",
        "",
        "| Table | Columns |",
        "| --- | --- |",
    ])
    lines.extend(
        f"| `{name}` | {_table_text(columns)} |"
        for name, columns in schema
    )
    lines.extend([
        "",
        "The `memories` table is the authoritative typed memory store; FTS, "
        "audit, lifecycle, privacy, and scope tables remain separate.",
    ])
    return "\n".join(lines) + "\n"


def _provider_setup(root: Path, source_digest: str) -> str:
    lines = _header("Provider setup", source_digest)
    lines.extend([
        "The deterministic core needs no model provider.",
        "",
        "## Local Ollama",
        "",
        "```powershell",
        "$env:ACR_PROVIDER = \"ollama\"",
        "$env:ACR_OLLAMA_URL = \"http://127.0.0.1:11434\"",
        "$env:ACR_OLLAMA_MODEL = \"your-local-model\"",
        "python -m acr_runtime.cli doctor --json",
        "```",
        "",
        "Ollama defaults to loopback and a remote endpoint requires an explicit "
        "provider override. Model capabilities are discovered before routing.",
        "",
        "## Deterministic tests",
        "",
        "`MockProvider` supplies offline chat, streaming, embedding, capability, "
        "and token-accounting contracts. CI does not require paid API keys.",
        "",
        "Never place credentials in CLI arguments, generated documentation, "
        "memory, or provider metadata. Use the governed secret-reference and "
        "exact-capability pathways.",
    ])
    return "\n".join(lines) + "\n"


def _troubleshooting(root: Path, source_digest: str) -> str:
    lines = _header("Troubleshooting", source_digest)
    lines.extend([
        "Start with:",
        "",
        "```powershell",
        "python -m acr_runtime.cli --db .acr/acr.db doctor --json",
        "python -m acr_runtime.cli --db .acr/acr.db status",
        "```",
        "",
        "| Symptom | Safe next check |",
        "| --- | --- |",
        "| Provider unavailable | Confirm the configured provider and local endpoint; deterministic features remain available. |",
        "| Model timeout | Inspect the retained task failure and retry only when the dependency is healthy. |",
        "| Database locked | Wait for the current writer, then retry; SQLite uses a bounded busy timeout. |",
        "| Schema mismatch | Run `acr doctor`; back up before an explicit migration. |",
        "| FTS unavailable | Check the Python SQLite build reported by `acr doctor`. |",
        "| Invalid or quarantined skill | Run `acr skills validate` and inspect retained validation evidence. |",
        "| Docker sandbox blocked | Verify the image is preinstalled; validation never pulls it. |",
        "| Suspected secret exposure | Run `acr secrets scan-staged` and do not persist the value. |",
        "| Corrupt memory | Stop writes, preserve a backup, inspect integrity, and repair from verified evidence. |",
        "",
        "Do not weaken permissions, bypass review, or auto-repair corrupted state "
        "to make a health check pass.",
    ])
    return "\n".join(lines) + "\n"


GENERATORS: dict[str, Callable[[Path, str], str]] = {
    "architecture-map.md": _architecture,
    "api-reference.md": _api_reference,
    "cli-reference.md": _cli_reference,
    "skill-format.md": _skill_format,
    "memory-schema.md": _memory_schema,
    "provider-setup.md": _provider_setup,
    "troubleshooting.md": _troubleshooting,
}


@dataclass(frozen=True)
class DocumentationProposal:
    proposal_id: str
    candidate_dir: str
    source_digest: str
    artifact_hashes: dict[str, str]

    def as_dict(self) -> dict[str, object]:
        return asdict(self)


class DocumentationAgent:
    def __init__(self, repository: str | Path) -> None:
        self.repository = Path(repository).resolve()
        if not (self.repository / "acr_runtime").is_dir():
            raise ValueError("Documentation repository is invalid")

    def render(self) -> tuple[str, dict[str, str]]:
        source_digest = _source_digest(self.repository)
        artifacts = {
            name: GENERATORS[name](self.repository, source_digest)
            for name in ARTIFACTS
        }
        return source_digest, artifacts

    def propose(
        self, candidate_dir: str | Path | None = None
    ) -> DocumentationProposal:
        source_digest, artifacts = self.render()
        hashes = {
            name: _hash_text(content) for name, content in artifacts.items()
        }
        proposal_id = _hash_text(_canonical({
            "generator_version": GENERATOR_VERSION,
            "source_digest": source_digest,
            "artifact_hashes": hashes,
        }))
        target = (
            self.repository
            / ".acr"
            / "documentation-proposals"
            / proposal_id
            if candidate_dir is None
            else Path(candidate_dir).resolve()
        )
        target.mkdir(parents=True, exist_ok=False)
        for name, content in artifacts.items():
            (target / name).write_text(content, encoding="utf-8", newline="\n")
        manifest = {
            "schema_version": 1,
            "generator_version": GENERATOR_VERSION,
            "proposal_id": proposal_id,
            "source_digest": source_digest,
            "artifact_hashes": hashes,
        }
        (target / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        return DocumentationProposal(
            proposal_id, str(target), source_digest, hashes
        )

    @staticmethod
    def _load_manifest(candidate: Path) -> dict[str, object]:
        payload = json.loads(
            (candidate / "manifest.json").read_text(encoding="utf-8")
        )
        required = {
            "schema_version", "generator_version", "proposal_id",
            "source_digest", "artifact_hashes",
        }
        if not isinstance(payload, dict) or set(payload) != required:
            raise ValueError("Documentation manifest shape is invalid")
        if payload["schema_version"] != 1:
            raise ValueError("Unsupported documentation manifest")
        if (
            not isinstance(payload["artifact_hashes"], dict)
            or set(payload["artifact_hashes"]) != set(ARTIFACTS)
        ):
            raise ValueError("Documentation artifact set is invalid")
        return payload

    def review(
        self,
        candidate_dir: str | Path,
        *,
        published_dir: str | Path | None = None,
    ) -> dict[str, object]:
        candidate = Path(candidate_dir).resolve()
        manifest = self._load_manifest(candidate)
        source_digest, current = self.render()
        actual_hashes = {
            name: _hash_bytes((candidate / name).read_bytes())
            for name in ARTIFACTS
        }
        expected_hashes = manifest["artifact_hashes"]
        fresh = (
            manifest["generator_version"] == GENERATOR_VERSION
            and manifest["source_digest"] == source_digest
            and actual_hashes == expected_hashes
            and all(
                (candidate / name).read_text(encoding="utf-8") == current[name]
                for name in ARTIFACTS
            )
        )
        published = (
            self.repository / "docs" / "generated"
            if published_dir is None
            else Path(published_dir).resolve()
        )
        changes = {
            name: (
                "missing"
                if not (published / name).is_file()
                else "unchanged"
                if _hash_bytes((published / name).read_bytes())
                == actual_hashes[name]
                else "changed"
            )
            for name in ARTIFACTS
        }
        review_hash = (
            _hash_text(_canonical({
                "proposal_id": manifest["proposal_id"],
                "source_digest": source_digest,
                "artifact_hashes": actual_hashes,
            }))
            if fresh else None
        )
        return {
            "proposal_id": manifest["proposal_id"],
            "fresh": fresh,
            "review_hash": review_hash,
            "changes": changes,
            "publishable": fresh and any(
                value != "unchanged" for value in changes.values()
            ),
        }

    def publish(
        self,
        candidate_dir: str | Path,
        *,
        review_hash: str,
        approved: bool,
        destination: str | Path | None = None,
    ) -> dict[str, object]:
        if not approved:
            raise PermissionError("Documentation publish requires --approve")
        candidate = Path(candidate_dir).resolve()
        target = (
            self.repository / "docs" / "generated"
            if destination is None
            else Path(destination).resolve()
        )
        review = self.review(candidate, published_dir=target)
        if not review["fresh"] or review["review_hash"] != review_hash:
            raise PermissionError(
                "Documentation review is stale or does not match the proposal"
            )
        target.mkdir(parents=True, exist_ok=True)
        written: list[str] = []
        for name in ARTIFACTS:
            temporary = target / f".{name}.{uuid.uuid4().hex}.tmp"
            temporary.write_bytes((candidate / name).read_bytes())
            os.replace(temporary, target / name)
            written.append(name)
        return {
            "proposal_id": review["proposal_id"],
            "published": written,
            "destination": str(target),
            "review_hash": review_hash,
        }
